global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'abcdedu'
    metrics_path: '/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['blue:8080', "green:8080"]
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']