CREATE TABLE representative_homework
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    homework_id   BIGINT NOT NULL,
    member_id   BIGINT,
    created_at  TIMESTAMP(6),
    updated_at  TIMESTAMP(6),
    PRIMARY KEY (id)
);

ALTER TABLE homeworks
    ADD COLUMN created_at TIMESTAMP(6);

ALTER TABLE homeworks
    ADD COLUMN updated_at TIMESTAMP(6);

ALTER TABLE homework_replys
    ADD COLUMN created_at TIMESTAMP(6);

ALTER TABLE homework_replys
    ADD COLUMN updated_at TIMESTAMP(6);

