CREATE TABLE representative_homework
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    homework_id   BIGINT NOT NULL,
    member_id   BIGINT NOT NULL,
    created_at  TIMESTAMP(6),
    updated_at  TIMESTAMP(6),
    PRIMARY KEY (id),
    FOREIGN KEY (homework_id) REFERENCES homeworks (id),
    FOREIGN KEY (member_id) REFERENCES members (id)
);

-- homeworks 테이블에 컬럼 추가
ALTER TABLE homeworks
    ADD COLUMN created_at TIMESTAMP(6);

ALTER TABLE homeworks
    ADD COLUMN updated_at TIMESTAMP(6);

-- homework_replys 테이블에 컬럼 추가
ALTER TABLE homework_replys
    ADD COLUMN created_at TIMESTAMP(6);

ALTER TABLE homework_replys
    ADD COLUMN updated_at TIMESTAMP(6);

